/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ZomeCallUnsignedNapi {
  cellId: Array<Array<number>>
  zomeName: string
  fnName: string
  payload: Array<number>
  capSecret?: Array<number>
  provenance: Array<number>
  nonce: Array<number>
  expiresAt: number
}
export interface ZomeCallNapi {
  cellId: Array<Array<number>>
  zomeName: string
  fnName: string
  payload: Array<number>
  capSecret?: Array<number>
  provenance: Array<number>
  nonce: Array<number>
  expiresAt: number
  signature: Array<number>
}
export function signZomeCallWithClient(zomeCallUnsignedJs: ZomeCallUnsignedNapi, connectionUrl: string, passphrase: string): Promise<ZomeCallNapi>
